### ISSUE TITLE
feat: add an option to let the user provide the ssh keys

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#1041]
# Feature request

https://github.com/konveyor/move2kube/blob/87d53a2b63fc7670cece3a0ae871c0f87e120c3f/common/sshkeys/sshkeys.go#L105-L107

Change to a `Select` type question and add an option to let the user provide the entire key PEM data as the answer.

## Context

This is useful when using the UI and generating a Tekton pipeline. The pipeline needs creds in order to clone the repo.
The UI/API server running in a different machine won't have access to the users' `~/.ssh` folder to get the keys.

**Comment by HarikrishnanBalagopal** [comment]
> Also, the one for kaniko: https://tekton.dev/docs/how-to-guides/kaniko-build-push/#container-registry-authentication

https://github.com/konveyor/move2kube/blob/87d53a2b63fc7670cece3a0ae871c0f87e120c3f/transformer/kubernetes/tektontransformer.go#L253-L262

https://github.com/konveyor/move2kube/blob/87d53a2b63fc7670cece3a0ae871c0f87e120c3f/transformer/kubernetes/tektontransformer.go#LL47C2-L47C29

**Comment by eloycoto** [comment]
Ok, regarding this:

I've just tried something like this:


```
    imageregistry:
      quay.io:
        logintype: use an existing pull secret
        pullsecret: parodosSecret
      namespace: parodos
      url: quay.io
```


And the secret is used on openshift-template/helm-chart/kustomize and yamls, but it's not part of the tekton pipeline workspaces at all.
