### ISSUE TITLE
Only one of the service is getting detected in language-platforms sample in Move2Kube UI

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#1159]
**Describe the bug**
Out of the 10 services in the [language platforms](https://github.com/konveyor/move2kube-demos/tree/main/samples/language-platforms), only 1 service is getting detected.

`m2k.plan`
```yaml
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: myproject
spec:
  sourceDir: ../move2kube-demos/samples/language-platforms
  services:
    language-platforms:
      - transformerName: Ruby-Dockerfile
        paths:
          ServiceDirectories:
            - .
        configs:
          OriginalName:
            originalName: language-platforms
```

**To Reproduce**
1. Run the `Plan` phase in Move2Kube UI using the [language-platforms.zip](https://github.com/konveyor/move2kube/files/14671820/language-platforms.zip)

<img width="1360" alt="Screenshot 2024-03-21 at 1 07 45 AM" src="https://github.com/konveyor/move2kube/assets/14867323/a7951245-a042-4f40-88bb-442513ecdfc8">

<img width="611" alt="Screenshot 2024-03-21 at 1 08 34 AM" src="https://github.com/konveyor/move2kube/assets/14867323/b8b24d89-909f-4023-8716-6b177aeaa7d0">

**Expected behavior**
Move2Kube should detect all the services in the given source code. The plan file should contain all the 10 services in the language-platforms.

**Desktop (please complete the following information):**
- OS: MacOS
- Browser: Firefox
- Version - quay.io/konveyor/move2kube-ui:v0.3.12-rc.0
 
<img width="641" alt="Screenshot 2024-03-21 at 1 11 37 AM" src="https://github.com/konveyor/move2kube/assets/14867323/1516dbbf-165a-4750-b1d2-b20e8ff59dee">
