### ISSUE TITLE
bug: customizations directory doesn't seem to be used during planning?

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#1194]
# Overview

Even though the `plan` command has a `--customizations` flag

```shell
$ move2kube plan --help
Discover and create a plan file based on an input directory

Usage:
  move2kube plan [flags]

Flags:
  -f, --config strings                Specify config file locations. By default we look for m2k-default-config.yaml
  -c, --customizations string         Specify directory or a git url (see https://move2kube.konveyor.io/concepts/git-support) where customizations are stored. By default we look for m2k-default-customizations
      --disable-local-execution       Allow files to be executed locally.
      --fail-on-empty-plan            If true, planning will exit with a failure exit code if no services are detected (and no default transformers are found).
  -h, --help                          help for plan
      --max-clone-size int            Max size in bytes when cloning a git repo. Default -1 is infinite (default -1)
  -n, --name string                   Specify the project name. (default "myproject")
  -p, --plan string                   Specify a file path to save plan to. (default "m2k.plan")
      --preset strings                Specify preset config to use.
      --set-config stringArray        Specify config key-value pairs.
  -s, --source string                 Specify source directory or a git url (see https://move2kube.konveyor.io/concepts/git-support).
  -t, --transformer-selector string   Specify the transformer selector.

Global Flags:
      --log-file string    File to store the logs in. By default it only prints to console.
      --log-level string   Set logging levels. (default "info")
```

The customization directory does not seem to actually be used during planning?

https://github.com/konveyor/move2kube/blob/c1a0f8a4db1014370e39d15a27a022a019e0e9c6/lib/planner.go#L48

The `CheckAndCopyCustomizations` function is defined in `utils.go`, tested in `utils_test.go` and only used in `transform.go`

![Image](https://github.com/user-attachments/assets/bfd8e6eb-a53d-4394-88eb-04adeee5b30e)

**Comment by HarikrishnanBalagopal** [comment]
```
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Transformer
metadata:
  name: JarWF
  labels:
    move2kube.konveyor.io/task: containerization
spec:
  class: "JarAnalyser"
  directoryDetect:
    levels: -1
  consumes: 
    Service: 
      merge: false
    Jar:
      merge: false
  produces:
    Dockerfile:
      disabled: false
    DockerfileForService:
      disabled: false
  config: 
    defaultJavaVersion: "17"
```
