### ISSUE TITLE
CF/Dockerfile: Funky character in PORT env var and duplicate containerPort elements in deployment yaml

### ISSUE THREAD

**Issue by asinghee** [konveyor/move2kube#136]
I see two weird things in the deployment yaml generated when running the local UI version on the `cloud-foundry` sample app in `move2kube-demos`:
1. funky character for the value of `PORT` env var
2. Duplicate `containerPort` elements for the same 8080 port in the `ports` section

I  targzipped the cloud-foundry sample folder,  and uploaded to the UI.  Did not run collect. Chose new Dockerfile plan  option.

Attaching screen shot.
Q&A cache in the follow up comment below.

![image](https://user-images.githubusercontent.com/20095283/97551223-b7226300-19f8-11eb-9824-1403c21dca93.png)

**Comment by asinghee** [comment]
Q&A  cache:
```
apiVersion: move2kube.konveyor.io/v1alpha1
kind: QACache
spec:
  solutions:
    - description: Which services should we expose?
      context:
        - An Ingress object will be created for every exposed service.
      solution:
        type: MultiSelect
        default:
          - move2kube-demo-cf
        options:
          - move2kube-demo-cf
        answer:
          - move2kube-demo-cf
      resolved: true
    - description: 'Select the registry where your images are hosted:'
      context:
        - You can always change it later by changing the yamls.
      solution:
        type: Select
        default:
          - docker.io
        options:
          - Other
          - docker.io
        answer:
          - docker.io
      resolved: true
    - description: 'Enter the namespace where the new images are pushed : '
      context:
        - 'Ex : cf'
      solution:
        type: Input
        default:
          - cf
        answer:
          - myns
      resolved: true
    - description: '[docker.io] What type of container registry login do you want to use?'
      context:
        - Docker login from config mode, will use the default config from your local machine.
      solution:
        type: Select
        default:
          - No authentication
        options:
          - Use existing pull secret
          - No authentication
          - UserName/Password
        answer:
          - Use existing pull secret
      resolved: true
    - description: '[docker.io] Enter the name of the pull secret : '
      context:
        - The pull secret should exist in the namespace where you will be deploying the application.
      solution:
        type: Input
        default:
          - ""
        answer:
          - blah
      resolved: true
```
