### ISSUE TITLE
Cloud foundry sample in move2kube-demos results in wrong plan with duplicates and wrong containerization options

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube#140]
```
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: myproject
spec:
  inputs:
    rootDir: samples/cloud-foundry
    services:
      move2kube-demo-cf:
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: NewDockerfile
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/dockerfiles/golang
            - m2kassets/dockerfiles/php
          sourceArtifacts:
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - ../../.
          buildArtifacts:
            SourceCode:
              - ../../.
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: S2I
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/s2i/golang
            - m2kassets/s2i/java
            - m2kassets/s2i/php
          sourceArtifacts:
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - ../../.
          buildArtifacts:
            SourceCode:
              - ../../.
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: CNB
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - cloudfoundry/cnb:cflinuxfs3
            - gcr.io/buildpacks/builder
          sourceArtifacts:
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - ../../.
          buildArtifacts:
            SourceCode:
              - ../../.
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: NewDockerfile
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/dockerfiles/nodejs
          sourceArtifacts:
            CfManifest:
              - manifest.yml
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: S2I
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/s2i/nodejs
          sourceArtifacts:
            CfManifest:
              - manifest.yml
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: CNB
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - cloudfoundry/cnb:cflinuxfs3
            - gcr.io/buildpacks/builder
          sourceArtifacts:
            CfManifest:
              - manifest.yml
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
    targetInfoArtifacts:
      KubernetesCluster:
        - cluster.yaml
  outputs:
    kubernetes:
      artifactType: Yamls
      clusterType: |
        default/c114-e-us-south-containers-cloud-ibm-com:32230/IAM#ashokponkumar@in.ibm.com
      ignoreUnsupportedKinds: true
```

**Comment by ashokponkumar** [comment]
Fixing #122  might fix this issue. This might be an issue with how parsing folders happens. @seshapad will be adding scenarios where it happens and when it does manifest.

**Comment by seshapad** [comment]
```move2kube plan -s samples/cloud-foundry/``` results in multiple incorrect detect scripts getting triggered as follows:
```
 - serviceName: move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: S2I
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/s2i/golang
            - m2kassets/s2i/java
            - m2kassets/s2i/php
          sourceArtifacts:
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - ../../.
          buildArtifacts:
            SourceCode:
              - ../../.
```

**Comment by HarikrishnanBalagopal** [comment]
Fixed by https://github.com/konveyor/move2kube/pull/163
```
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: myproject
spec:
  inputs:
    rootDir: samples/cloud-foundry
    services:
      move2kube-demo-cf:
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: NewDockerfile
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/dockerfiles/nodejs
          sourceArtifacts:
            CfManifest:
              - manifest.yml
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: S2I
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - m2kassets/s2i/nodejs
          sourceArtifacts:
            CfManifest:
              - manifest.yml
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
        - serviceName: move2kube-demo-cf
          serviceRelPath: /move2kube-demo-cf
          image: move2kube-demo-cf:latest
          translationType: Cfmanifest2Kube
          containerBuildType: CNB
          sourceType:
            - Directory
            - CfManifest
          targetOptions:
            - cloudfoundry/cnb:cflinuxfs3
            - gcr.io/buildpacks/builder
          sourceArtifacts:
            CfManifest:
              - manifest.yml
            CfRunningManifest:
              - cfapps.yaml
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
    targetInfoArtifacts:
      KubernetesCluster:
        - cluster.yaml
  outputs:
    kubernetes:
      artifactType: Yamls
      targetCluster:
        type: |
          default/c114-e-us-south-containers-cloud-ibm-com:32230/IAM#ashokponkumar@in.ibm.com
      ignoreUnsupportedKinds: true
```
