### ISSUE TITLE
Add optional liveliness and readiness probes.

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#167]
Add `livenessProbe` and `readinessProbe` to each deployment.

Not sure how to do this in case of k8s yamls without using placeholdes `<TODO: fill in the path>` `<TODO: fill in the port>`.

In the case of helm it should be parameterized. Something like
```
if {{ .svcName.enableProbes }}
    livenessProbe:
      httpGet:
        path: {{ .svcName.svcRelPath }}
        port: {{ .svcName.ports[0] }}
      initialDelaySeconds: 5
      periodSeconds: 5
endif
```
It should work out of the box and the probles can be enabled by the user by filling in the right values in `values.yaml`
