### ISSUE TITLE
Python service doesn't support the Dockerfile containerization

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#447]
**Describe the bug**
The sample python app from move2kube-demos/samples doesn't support Dockerfile containerization.
```
python:
        - serviceName: python
          serviceRelPath: /python
          image: python:latest
          translationType: Containerize
          containerBuildType: CNB
          sourceType:
            - Directory
          targetOptions:
            - gcr.io/buildpacks/builder
          sourceArtifacts:
            SourceCode:
              - python
          buildArtifacts:
            SourceCode:
              - python
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
          repoInfo:
            gitRepoDir: ../..
            gitRepoURL: https://github.com/konveyor/move2kube-demos.git
            gitRepoBranch: main
            targetPath: ""
```

**To Reproduce**
1. Run `move2kube plan -s samples/language-platforms`
2. Select `NewDockerfile` as the containerization mode.

```
WARN[0258] Ignoring service python, since it does not support any selected containerization technique.
```

**Screenshots**
<img width="1792" alt="Screenshot 2021-03-09 at 11 38 40 AM" src="https://user-images.githubusercontent.com/14867323/110430354-3ffd8980-80d2-11eb-809d-6ffeb2361082.png">
