### ISSUE TITLE
[Question] Cannot make run a Dockerfile customization

### ISSUE THREAD

**Issue by lordofthejars** [konveyor/move2kube#584]
**Describe the bug**

Cannot make run Dockerfile customization, it always takes the default one instead of the one I tried to configure.

**To Reproduce**

1. Clone https://github.com/redhat-developer-demos/konveyor-tutorial
2. Example is located at https://github.com/redhat-developer-demos/konveyor-tutorial/tree/main/move2kube/extending
3. I run `move2kube plan -s extending` and `move2kube translate -c`

**Expected behavior**

Containers Dockerfile created from custom `templates` directory

**Screenshots**

**Desktop (please complete the following information):**

move2kube version
v0.2.0-alpha.3

**Comment by ashokponkumar** [comment]
Thanks @lordofthejars for the issue. Can you please share the m2k.plan file that was generated?

**Comment by lordofthejars** [comment]
I am not saying it is a bug as I might be doing something wrong but the `sh` has `X` permissions and as you can see always returns a document, so maybe I am placing them in the wrong place.

```
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Plan
metadata:
  name: myproject
spec:
  inputs:
    rootDir: extending
    services:
      extending:
        - serviceName: extending
          serviceRelPath: /extending
          image: extending:latest
          translationType: Containerize
          containerBuildType: NewDockerfile
          sourceType:
            - Directory
          targetOptions:
            - m2kassets/dockerfiles/javagradle
          sourceArtifacts:
            SourceCode:
              - .
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
      myproject:
        - serviceName: myproject
          serviceRelPath: /myproject
          image: myproject:latest
          translationType: Dockerfile
          containerBuildType: ReuseDockerfile
          sourceType:
            - Directory
          targetOptions:
            - templates/Dockerfile
          sourceArtifacts:
            Dockerfile:
              - templates/Dockerfile
          buildArtifacts:
            SourceCode:
              - .
          updateContainerBuildPipeline: true
          updateDeployPipeline: true
  outputs:
    kubernetes:
      artifactType: Yamls
      targetCluster:
        type: Kubernetes
```
