### ISSUE TITLE
bug: multi-select questions use the options provided as a sub key without quoting them

### ISSUE THREAD

**Issue by HarikrishnanBalagopal** [konveyor/move2kube#847]
**Describe the bug**
When the options contain special characters like `.` it causes the issues.
The options are used as sub-keys and gets split into parts.

```
move2kube:
  containerruntime: docker
  minreplicas: "2"
  services:
    eShop:
      childProjects:
        eShop:
          Web:
            enable: true
          WebApi:
            enable: true
        eShop.Web:
          ports:
            - "51047"
            - "51048"
        eShop.WebApi:
          ports:
            - "51044"
      dockerfileType: build stage in base image
      enable: true
```

**To Reproduce**
1. Create a sample input (like DotNet Core/Java) with child projects and have a child project with a name like `eShop.WebApi`
2. `move2kube transform` the sample input
3. Look at the `m2kconfig.yaml` generated afterwards.

**Expected behavior**
```
move2kube:
  containerruntime: docker
  minreplicas: "2"
  services:
    eShop:
      childProjects:
        eShop.Web:
          enable: true
          ports:
            - "51047"
            - "51048"
        eShop.WebApi:
          enable: true
          ports:
            - "51044"
      dockerfileType: build stage in base image
      enable: true
```

**Additional context**

Found by @binypanackal
