### ISSUE TITLE
Move2Kube is creating the image pull secret yaml if selecting use an existing pull secret during QA

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube#902]
**Describe the bug**
Move2Kube is generating the image pull secret yaml file when I select "use an existing pull secret" for container registry login. This new image pull secret file has the same name as that of the existing pull secret file on the Kubernetes cluster and it overrides the existing pull secret file and thus pods fail to pull the image from the private registry.

Also, it creates the image pull secret file if I select "no authentication".

**To Reproduce**
Run `move2kube transform` and select "use an existing pull secret" in the container registry login question.
```console
? [quay.io] What type of container registry login do you want to use?
ID: move2kube.target.imageregistry."quay.io".logintype
Hints:
- Docker login from config mode, will use the default config from your local machine.

 use an existing pull secret
? [quay.io] Enter the name of the pull secret : 
ID: move2kube.target.imageregistry."quay.io".pullsecret
Hints:
- The pull secret should exist in the namespace where you will be deploying the application.

 all-icr-io
INFO[0049] Transformer ArgoCD Done
```

It created `all-icr-io-secret.yaml` file.

```console
$ ls myproject/deploy/yamls
all-icr-io-secret.yaml          frontend-vcapasenv-secret.yaml  inventory-vcapasenv-secret.yaml
customers-deployment.yaml       gateway-deployment.yaml         myproject-new-ingress.yaml
customers-service.yaml          gateway-service.yaml            orders-deployment.yaml
customers-vcapasenv-secret.yaml gateway-vcapasenv-secret.yaml   orders-service.yaml
frontend-deployment.yaml        inventory-deployment.yaml       orders-vcapasenv-secret.yaml
frontend-service.yaml           inventory-service.yaml
```

Also, selecting "no authentication" created `quay-io-imagepullsecret-secret.yaml` file.
```console
? [quay.io] What type of container registry login do you want to use?
ID: move2kube.target.imageregistry."quay.io".logintype
Hints:
- Docker login from config mode, will use the default config from your local machine.

 no authentication
INFO[0006] Transformer ArgoCD Done
```

```console
ls myproject-new/deploy/yamls
customers-deployment.yaml           inventory-deployment.yaml
customers-service.yaml              inventory-service.yaml
customers-vcapasenv-secret.yaml     inventory-vcapasenv-secret.yaml
frontend-deployment.yaml            myproject-new1-ingress.yaml
frontend-service.yaml               orders-deployment.yaml
frontend-vcapasenv-secret.yaml      orders-service.yaml
gateway-deployment.yaml             orders-vcapasenv-secret.yaml
gateway-service.yaml                quay-io-imagepullsecret-secret.yaml
gateway-vcapasenv-secret.yaml
```

**Expected behavior**
The image pull secret file should not be created if selecting "use an existing pull secret".

**Desktop (please complete the following information):**
 - move2kube version -l
   version: v0.3.0+unreleased
   gitCommit: e58c21caabcd2cdb7dd0f7f0fcc1e6afc8a35986
   gitTreeState: clean
   goVersion: go1.18.1
   platform: darwin/amd64

**Comment by HarikrishnanBalagopal** [comment]
Related to this. Move2Kube also seems to configure a pull secret even if you choose `No Authentication`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: golang
  name: golang
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      move2kube.konveyor.io/service: golang
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: golang
      name: golang
    spec:
      containers:
        - image: quay.io/myproject/golang:latest
          imagePullPolicy: Always
          name: golang
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: quay-io-imagepullsecret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
```
