### ISSUE TITLE
bug: Paramaterization not working for Kustomize with below configuration

### ISSUE THREAD

**Issue by seshapad** [konveyor/move2kube#954]
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Parameterizer
metadata:
  name: deployment-parameterizers
spec:
  parameterizers:
    - target: "spec.replicas"
      template: "${common.replicas}"
      default: 10
      filters:
        - kind: Deployment
          apiVersion: ".*/v1.*"
        - kind: WebSphereLibertyApplication
          apiVersion: ".*/v1.*"
    - target: 'spec.template.spec.containers.[containerName:name].image'
      template: '${imageregistry.url}/${imageregistry.namespace}/${services.$(metadataName).containers.$(containerName).image.name}:${services.$(metadataName).containers.$(containerName).image.tag}'
      default: quay.io/konveyor/myimage:latest
      filters:
        - kind: Deployment
          apiVersion: ".*/v1.*"
    - target: 'spec.applicationImage'
      template: '${imageregistry.url}/${imageregistry.namespace}/${services.$(metadataName).containers.libertyImage.name}:${services.$(metadataName).containers.libertyImage.tag}'
      default: quay.io/konveyor/myimage:latest
      filters:
        - kind: WebSphereLibertyApplication
          apiVersion: ".*/v1.*"

**Comment by HarikrishnanBalagopal** [comment]
Formatted
```yaml
apiVersion: move2kube.konveyor.io/v1alpha1
kind: Parameterizer
metadata:
  name: deployment-parameterizers
spec:
  parameterizers:
    - target: "spec.replicas"
      template: "${common.replicas}"
      default: 10
      filters:
        - kind: Deployment
          apiVersion: "./v1."
        - kind: WebSphereLibertyApplication
          apiVersion: "./v1."
    - target: "spec.template.spec.containers.[containerName:name].image"
      template: "${imageregistry.url}/${imageregistry.namespace}/${services.$(metadataName).containers.$(containerName).image.name}:${services.$(metadataName).containers.$(containerName).image.tag}"
      default: quay.io/konveyor/myimage:latest
      filters:
        - kind: Deployment
          apiVersion: "./v1."
    - target: "spec.applicationImage"
      template: "${imageregistry.url}/${imageregistry.namespace}/${services.$(metadataName).containers.libertyImage.name}:${services.$(metadataName).containers.libertyImage.tag}"
      default: quay.io/konveyor/myimage:latest
      filters:
        - kind: WebSphereLibertyApplication
          apiVersion: "./v1."
```

**Comment by HarikrishnanBalagopal** [comment]
@seshapad can you describe the bug?
1. Steps to reproduce
2. Which version of Move2Kube
3. What output you are expecting
4. The actual output

**Comment by HarikrishnanBalagopal** [comment]
Is it just the last parameterizer that's not working or all of them?
```yaml
    - target: "spec.applicationImage"
      template: "${imageregistry.url}/${imageregistry.namespace}/${services.$(metadataName).containers.libertyImage.name}:${services.$(metadataName).containers.libertyImage.tag}"
      default: quay.io/konveyor/myimage:latest
      filters:
        - kind: WebSphereLibertyApplication
          apiVersion: "./v1."
```
